version: '3'
services:
  nginx:
    container_name: "my-nginx"
    image: nginx
    restart: always
    # 端口映射
    ports:
      - "80:80"
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    # 其中/d/dockerLNMP/nginx/nginx.conf文件需提前创建
    volumes:
      - "/d/dockerLNMP/nginx/log:/var/log/nginx"
      - "/d/dockerLNMP/html:/usr/share/nginx/html"
      - "/d/dockerLNMP/nginx/conf.d:/etc/nginx/conf.d"
      - "/d/dockerLNMP/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - my_net
  php:
    container_name: "my-php"
    build: ./php
    image: php:7.4-withext
    restart: always
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - "/d/dockerLNMP/html:/var/www/html"
      - "/d/dockerLNMP/php/logs:/var/log/php"
      - "/d/dockerLNMP/php/etc:/usr/local/etc"
    networks:
      - my_net
  mysql:
    container_name: "my-mysql"
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/d/dockerLNMP/mysql/data:/var/lib/mysql"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - my_net
  redis:
    container_name: "my-redis"
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/d/dockerLNMP/redis/data:/data"
    command: redis-server --port 6379 --appendonly yes # 开启数据持久化
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1